# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"survey": "02_evaluate.ipynb",
         "wrapper": "02_wrapper.ipynb"}

modules = ["survey.py",
           "evaluate.py",
           "wrapper.py"]

doc_url = "https://brockmanmatt.github.io/OpenAISurveyWrapper/"

git_url = "https://github.com/brockmanmatt/OpenAISurveyWrapper/tree/master/"

def custom_doc_links(name): return None
