# AUTOGENERATED! DO NOT EDIT! File to edit: 00_wrapper.ipynb (unless otherwise specified).

__all__ = ['wrapper']

# Cell
import openai, pandas, numpy

# Cell
class wrapper:
    """
    Wrapper holds the OpenAI
    """